apiVersion: v1
kind: Pod
metadata:
  name: kunal-app
  labels: 
    app: new-app
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports: 
    - containerPort: 80
      protocol: TCP

    