apiVersion: v1
kind: Service
metadata: 
  name: my-ser
spec: 
  selector:
    app: new-app
  type: NodePort
  ports: 
    - protocol: TCP 
      port: 80
      targetPort: 
  ports: 
    - protocol: TCP 
      port: 80
      targetPort: 8080