apiVersion: v1
kind: ReplicationController
metadata:
  name: rpcont
  labels:
    app: rc-app
spec: 
    selector: 
      app: rc-app 
    replicas: 4
    template:   
      metadata:
        labels:
          name: nginxapp
          app: rc-app
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest 
            ports:
                - containerPort: 80
                  protocol: TCP

      