apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
  name: rs
  labels:
    app: reps
spec:
    selector: 
    matchExpressions:
      - {key: app, operator: In, values: [reps]}
    replicas: 4
    template:
      metadata:
        labels:
          name: nginxapp
          app: reps
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest 
            ports:
                - containerPort: 80
                  protocol: TCP