apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment
  labels:
    app: deploy-app

spec:
  selector:
    matchLabels:
      app: deploy-app
  replicas: 3
  template:
    metadata:
      name: deployment
      labels:
        app: deploy-app
    spec:
      containers:
      - name: deployment
        image: nginx:latest
        ports:
        - containerPort: 80