apiVersion: v1
kind: Pod 
metadata: 
  name: prctpod
  namespace: dev
  labels: 
    app: my-app
spec: 
  containers: 
    - name: nginx
      image: nginx:latest
      ports: 
        - containerPort: 80
          protocol: TCP
          name: nginx
--- 
apiVersion: v1
kind: Service 
metadata: 
  name: my-ser
  namespace: dev 
spec: 
  selector: 
    app: my-app 
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
    name: nginx 
